# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

show_downloads: false
title: mark goldstein


logo: /assets/img/yz.jpg
description: >- # this means to ignore newlines until "baseurl:"
    
#logo: /assets/img/dec2021.jpeg
#description: >- # this means to ignore newlines until "baseurl:"
    
#logo: /assets/img/setar_cropped_sq.png
#description: >- # this means to ignore newlines until "baseurl:"
#    wall of setar

#logo: /assets/img/tokyoplant.jpeg
#description: >- # this means to ignore newlines until "baseurl:"
#    a lotus plant at ueno station
#logo: /assets/img/fotobukhar.jpeg
#description: >- # this means to ignore newlines until "baseurl:"
#    walking in lower east side
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
domain: marikgoldstein.github.io       
# if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://marikgoldstein.github.io  
# the base hostname and protocol for your site, e.g. http://example.com


twitter_username: jekyllrb
github_username:  jekyll

# Build settings
#theme: minima
theme: jekyll-theme-minimal


plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



